TC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from utilisateur.views import CustomLoginView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', CustomLoginView.as_view(), name='home'),  # Page d'accueil redirigée vers login
    path('admin/', admin.site.urls),
    path('accounts/',include('utilisateur.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

utilisateur/urls.py
from django.urls import path
from .views import (
    CustomLoginView, register_patient, register_doctor, custom_logout,
    patient_dashboard, doctor_dashboard, ConsultationCreateView,
    CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView, about_us, update_consultation_status
)

app_name = 'utilisateur'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/patient/', register_patient, name='register_patient'),
    path('register/doctor/', register_doctor, name='register_doctor'),
    path('logout/', custom_logout, name='logout'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('patient/dashboard/', patient_dashboard, name='patient_dashboard'),
    path('doctor/dashboard/', doctor_dashboard, name='doctor_dashboard'),
    path("consultations/<int:consultation_id>/status/<str:status>/", update_consultation_status, name="update_consultation_status"),
    # path('consultations/', ConsultationListView.as_view(), name='consultation_list'),
    path('consultations/create/', ConsultationCreateView.as_view(), name='consultation_create'),
    path('about-us/', about_us, name='about_us'),
]
# from django.urls import path
# from .views import (about_us, CustomLoginView, register_patient, register_doctor, custom_logout,
#     CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView,
#     patient_dashboard, doctor_dashboard, ConsultationListView, ConsultationCreateView)



# app_name = 'utilisateur'

# urlpatterns = [
#     path('', CustomLoginView.as_view(), name='home'),  # Page d'accueil redirigée vers login
#     path('login/', CustomLoginView.as_view(), name='login'),
#     path('register/patient/', register_patient, name='register_patient'),
#     path('register/doctor/', register_doctor, name='register_doctor'),
#     path('logout/', custom_logout, name='logout'),
#     path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
#     path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
#     path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
#     path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
#     path('patient/dashboard/', patient_dashboard, name='patient_dashboard'),
#     path('doctor/dashboard/', doctor_dashboard, name='doctor_dashboard'),
#     path('consultations/', ConsultationListView.as_view(), name='consultation_list'),
#     path('consultations/create/', ConsultationCreateView.as_view(), name='consultation_create'),
#     # path('about-us/', lambda request: render(request, 'about_us.html'), name='about_us'),  #
#     path('about-us/', about_us, name='about_us'),
    
#     # ## Juste une simulation des Urls  
#     # path('login/', CustomLoginView.as_view(), name='login'),
#     # path('register/patient/', register_patient, name='register_patient'),
#     # path('register/doctor/', register_doctor, name='register_doctor'),
#     # path('logout/', custom_logout, name='logout'),
#     # path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
#     # path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
#     # path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
#     # path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
#     # path('patient/dashboard/', patient_dashboard, name='patient_dashboard'),
#     # path('doctor/dashboard/', doctor_dashboard, name='doctor_dashboard'),
#     # path('consultations/', ConsultationListView.as_view(), name='consultation_list'),
#     # path('consultations/create/', ConsultationCreateView.as_view(), name='consultation_create'),
    
# ]

templates/base.html
{% load static  %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% comment %} <meta http-equiv = "refresh" content = "0 ; url = './html/index.html'"/> {% endcomment %}
  <title>Studiova</title>
  <link rel="shortcut icon" type="image/png" href="{% static './assets/images/logos/favicon.svg' %}" />
  <link rel="stylesheet" href="{% static './assets/libs/owl.carousel/dist/assets/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static './assets/libs/aos-master/dist/aos.css' %}">
  <link rel="stylesheet" href="{% static  './assets/css/styles.css' %}" />
</head>

<body>
<!-- NOTE: Please go to the './html/index.html' file to edit -->  toi la 
</body>

</html>

templates/base_bks.html
<!DOCTYPE html>
<html lang="fr">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}TConsultGuinee{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static './assets/images/logos/favicon.svg' %}" />
    <link rel="stylesheet" href="{% static './assets/libs/owl.carousel/dist/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static './assets/libs/aos-master/dist/aos.css' %}">
    <link rel="stylesheet" href="{% static './assets/css/styles.css' %}" />
</head>

<body>
    <!-- Header -->
    <header class="header border-4 border-primary border-top position-fixed start-0 top-0 w-100">
        <div class="container">
            <div class="header-wrapper d-flex align-items-center justify-content-between">
                <div class="logo">
                    <a href="{% url 'utilisateur:home' %}" class="logo-white">
                        <img src="{% static './assets/images/logos/logo-white.svg' %}" alt="logo" class="img-fluid">
                    </a>
                    <a href="{% url 'utilisateur:home' %}" class="logo-dark">
                        <img src="{% static './assets/images/logos/logo-dark.svg' %}" alt="logo" class="img-fluid">
                    </a>
                </div>
                <div class="d-flex align-items-center gap-4">
                    <div class="btn-group">
                        <button class="btn btn-secondary toggle-menu round-45 p-2 d-flex align-items-center justify-content-center bg-white rounded-circle"
                                type="button" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">
                            <iconify-icon icon="solar:hamburger-menu-line-duotone" class="menu-icon fs-8 text-dark"></iconify-icon>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end p-4">
                            <div class="d-flex flex-column gap-6">
                                <div class="hstack justify-content-between border-bottom pb-6">
                                    <p class="mb-0 fs-5 text-dark">Menu</p>
                                    <button type="button" class="btn-close opacity-75" aria-label="Close"></button>
                                </div>
                                <div class="d-flex flex-column gap-3">
                                    <ul class="header-menu list-unstyled mb-0 d-flex flex-column gap-2">
                                        <li class="header-item">
                                            <a href="{% url 'utilisateur:home' %}" aria-current="true"
                                               class="header-link active hstack gap-2 fs-7 fw-bold text-dark">
                                                <img src="{% static './assets/images/svgs/secondary-leaf.svg' %}" alt="" width="20" height="20"
                                                     class="img-fluid animate-spin">Home
                                            </a>
                                        </li>
                                        <li class="header-item">
                                            <a href="{% url 'utilisateur:about_us' %}" class="header-link hstack gap-2 fs-7 fw-bold text-dark">
                                                <img src="{% static './assets/images/svgs/secondary-leaf.svg' %}" alt="" width="20" height="20"
                                                     class="img-fluid animate-spin">About
                                            </a>
                                        </li>
                                        {% if user.is_authenticated %}
                                            <li class="header-item">
                                                <a href="{% if user.is_patient %}{% url 'utilisateur:patient_dashboard' %}{% else %}{% url 'utilisateur:doctor_dashboard' %}{% endif %}"
                                                   class="header-link hstack gap-2 fs-7 fw-bold text-dark">
                                                    <img src="{% static './assets/images/svgs/secondary-leaf.svg' %}" alt="" width="20" height="20"
                                                         class="img-fluid animate-spin">Dashboard
                                                </a>
                                            </li>
                                            <li class="header-item">
                                                <a href="{% url 'utilisateur:logout' %}" class="header-link hstack gap-2 fs-7 fw-bold text-dark">
                                                    <img src="{% static './assets/images/svgs/secondary-leaf.svg' %}" alt="" width="20" height="20"
                                                         class="img-fluid animate-spin">Logout
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="header-item">
                                                <a href="{% url 'utilisateur:login' %}" class="header-link hstack gap-2 fs-7 fw-bold text-dark">
                                                    <img src="{% static './assets/images/svgs/secondary-leaf.svg' %}" alt="" width="20" height="20"
                                                         class="img-fluid animate-spin">Sign In
                                                </a>
                                            </li>
                                            <li class="header-item">
                                                <a href="{% url 'utilisateur:register_patient' %}" class="header-link hstack gap-2 fs-7 fw-bold text-dark">
                                                    <img src="{% static './assets/images/svgs/secondary-leaf.svg' %}" alt="" width="20" height="20"
                                                         class="img-fluid animate-spin">Sign Up (Patient)
                                                </a>
                                            </li>
                                            <li class="header-item">
                                                <a href="{% url 'utilisateur:register_doctor' %}" class="header-link hstack gap-2 fs-7 fw-bold text-dark">
                                                    <img src="{% static './assets/images/svgs/secondary-leaf.svg' %}" alt="" width="20" height="20"
                                                         class="img-fluid animate-spin">Sign Up (Doctor)
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                    <div class="hstack gap-3">
                                        {% if not user.is_authenticated %}
                                            <a href="{% url 'utilisateur:login' %}"
                                               class="btn btn-outline-light fs-6 bg-white px-3 py-2 text-dark w-50 hstack justify-content-center">Sign In</a>
                                            <a href="{% url 'utilisateur:register_patient' %}"
                                               class="btn btn-dark text-white fs-6 bg-dark px-3 py-2 w-50 hstack justify-content-center">Sign Up</a>
                                        {% endif %}
                                    </div>
                                </div>
                                <div>
                                    <a class="text-dark" href="tel:+1-212-456-7890">+1-212-456-7890</a>
                                    <a class="fs-8 text-dark fw-bold" href="mailto:info@wrappixel.com">info@wrappixel.com</a>
                                </div>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Page Wrapper -->
    <div class="page-wrapper overflow-hidden">
        {% block content %}{% endblock %}
    </div>

    <footer class="footer bg-dark py-5 py-lg-11 py-xl-12">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 mb-8 mb-xl-0">
                    <div class="d-flex flex-column gap-8 pe-xl-5">
                        <h2 class="mb-0 text-white">Build something together?</h2>
                        <div class="d-flex flex-column gap-2">
                            <a href="mailto:info@wrappixel.com" class="link-hover hstack gap-3 text-white fs-5">
                                <iconify-icon icon="lucide:arrow-up-right" class="fs-7 text-primary"></iconify-icon>
                                info@wrappixel.com
                            </a>
                            <a href="https://maps.app.goo.gl/hpDp81fqzGt5y4bC8" target="_blank"
                               class="link-hover hstack gap-3 text-white fs-5">
                                <iconify-icon icon="lucide:map-pin" class="fs-7 text-primary"></iconify-icon>
                                info@wrappixel.com
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-xl-2 mb-8 mb-xl-0">
                    <ul class="footer-menu list-unstyled mb-0 d-flex flex-column gap-2">
                        <li><a class="link-hover fs-5 text-white" href="{% url 'utilisateur:home' %}">Home</a></li>
                        <li><a class="link-hover fs-5 text-white" href="{% url 'utilisateur:about_us' %}">About</a></li>
                        <li><a class="link-hover fs-5 text-white" href="#services">Services</a></li>
                        <li><a class="link-hover fs-5 text-white" href="#">Work</a></li>
                        <li><a class="link-hover fs-5 text-white" href="#">Terms</a></li>
                        <li><a class="link-hover fs-5 text-white" href="#">Privacy Policy</a></li>
                        <li><a class="link-hover fs-5 text-white" href="#">Error 404</a></li>
                    </ul>
                </div>
                <div class="col-md-4 col-xl-2 mb-8 mb-xl-0">
                    <ul class="footer-menu list-unstyled mb-0 d-flex flex-column gap-2">
                        <li><a class="link-hover fs-5 text-white" href="#">Facebook</a></li>
                        <li><a class="link-hover fs-5 text-white" href="#">Instagram</a></li>
                        <li><a class="link-hover fs-5 text-white" href="#">Twitter</a></li>
                    </ul>
                </div>
                <div class="col-md-4 col-xl-3 mb-8 mb-xl-0">
                    <p class="mb-0 text-white text-opacity-70 text-md-end">© TConsultGuinee copyright 2025</p>
                </div>
            </div>
        </div>
        <p class="mb-0 text-white text-opacity-70 text-md-center mt-10">Distributed by <a class="text-white" href="https://www.themewagon.com" target="_blank">ThemeWagon</a></p>
    </footer>

    <div class="get-template hstack gap-2">
        <button class="btn bg-primary p-2 round-52 rounded-circle hstack justify-content-center flex-shrink-0"
                id="scrollToTopBtn">
            <iconify-icon icon="lucide:arrow-up" class="fs-7 text-dark"></iconify-icon>
        </button>
    </div>

    <script src="{% static './assets/libs/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static './assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static './assets/libs/owl.carousel/dist/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/libs/aos-master/dist/aos.js' %}"></script>
    <script src="{% static './assets/js/custom.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/iconify-icon@1.0.8/dist/iconify-icon.min.js"></script>
    <script>
        document.getElementById('scrollToTopBtn').addEventListener('click', function() {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
    </script>
</body>
</html>